name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build Docker Image
        run: |
          docker pull ghcr.io/blacksmith/img-cacher/worker:latest
          docker build --cache-from ghcr.io/blacksmith/img-cacher/worker:latest -t ghcr.io/blacksmith/img-cacher/worker:latest . --target worker
          docker pull ghcr.io/blacksmith/img-cacher/main:latest
          docker build --cache-from ghcr.io/blacksmith/img-cacher/main:latest -t ghcr.io/blacksmith/img-cacher/main:latest . --target main
          docker tag ghcr.io/blacksmith/img-cacher/worker:latest ghcr.io/blacksmith/img-cacher/worker:${{ github.sha }}
          docker tag ghcr.io/blacksmith/img-cacher/main:latest ghcr.io/blacksmith/img-cacher/main:${{ github.sha }}

      - name: Push Docker Image to GitHub Container Registry
        run: |
          docker push ghcr.io/blacksmith/img-cacher/worker:${{ github.sha }}
          docker push ghcr.io/blacksmith/img-cacher/main:${{ github.sha }}
          docker push ghcr.io/blacksmith/img-cacher/worker:latest
          docker push ghcr.io/blacksmith/img-cacher/main:latest
        
